services:
  - type: web
    name: forex-telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8549981793:AAE_2GSzJ1G3Pz0g6uhaGAK2JaqoBJ-IQmM